
name: p4e-example-app

trigger:
  - master

variables:
  - group: p4e-example-app
  - name: Azure.CreateResources
    value: 'true' # Update Azure.CreateResources to false if you have already created resources like resource group and azure container registry.
  - name: ImageName
    value: p4eexampleapp
  - name: Azure.Location
    value: 'Japan East'
  - name: Azure.ACR.RegistryLocation
    value: 'Japan East'
  - name: Azure.ACR.Sku
    value: Standard
  - name: Azure.WebbApp.AppInsightsLocation
    value: 'Japan East'
  - name: Azure.WebbApp.Sku
    value: Standard
  - name: Azure.WebbApp.SkuCode
    value: S1
  - name: Azure.Database.Name
    value: webapp

stages:
  - stage: CreateResources
    jobs:
      - job: CreateResources
        displayName: Create resources
        condition: and(succeeded(), eq(variables['Azure.CreateResources'], 'true'))
        pool:
          vmImage: 'Ubuntu-16.04'
        steps:
          - template: templates/createresources-steps.yml

  - stage: UnitTest
    jobs:
      - job: UnitTest
        displayName: UnitTest
        condition: succeeded()
        pool:
          vmImage: 'Ubuntu-16.04'
        steps:
          - template: templates/unittest-steps.yml

  - stage: Build
    jobs:
      - job: Build
        displayName: Build
        condition: succeeded()
        pool:
          vmImage: 'Ubuntu-16.04'
        variables:
          - group: p4e-example-app
        steps:
          - template: templates/buils-steps.yml

  - stage: Staging
    jobs:
      - deployment: Deploy
        pool:
          vmImage: 'Ubuntu-16.04'
        environment: '$(WEBAPP_NAME)-staging'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureRmWebAppDeployment@3
                  displayName: 'Deploy Azure App Service'
                  inputs:
                    azureSubscription: $(SUBSCRIPTION_NAME)
                    appType: applinux
                    WebAppName: $(WEBAPP_NAME)
                    DeployToSlotFlag: true
                    ResourceGroupName: $(RESOURCE_GROUP_NAME)
                    SlotName: staging
                    DockerNamespace: '$(REPOSITORY_NAME).azurecr.io'
                    DockerRepository: $(ImageName)
                    DockerImageTag: '$(Build.BuildId)'
                    TakeAppOfflineFlag: true
                    UseWebDeploy: true
                    RenameFilesFlag: true

  - stage: Production
    jobs:
      - deployment: Deploy
        pool:
          vmImage: 'Ubuntu-16.04'
        environment: '$(WEBAPP_NAME)-production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureAppServiceManage@0
                  displayName: 'Swap Slots'
                  inputs:
                    azureSubscription: $(SUBSCRIPTION_NAME)
                    WebAppName: $(WEBAPP_NAME)
                    ResourceGroupName: $(RESOURCE_GROUP_NAME)
                    SourceSlot: staging
