
name: p4e-example-app

trigger:
  - master

variables:
  - group: p4e-example-app

jobs:
  - job:
    displayName: UnitTest
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - template: templates/unittest-steps.yml

  - job: Build
    pool:
      vmImage: 'Ubuntu-16.04'
    variables:
      - group: p4e-example-app
    steps:
      - template: templates/buils-steps.yml
