version: '3.1'

services:
  p4e-database-ci:
    container_name: p4e-database-ci
    image: postgres:11.5-alpine
    ports:
      - '5432:5432'
    tmpfs:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "passw0rd"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
      POSTGRES_USER: "webapp"

  p4e-app-ci:
    container_name: p4e-app-ci
    build:
      context: ./app
      dockerfile: Dockerfile.ci
    depends_on:
      - p4e-database-ci
    ports:
      - '80:80'
    environment:
      APP_ENV: ci
      DB_HOST: p4e-database-ci
      DB_USER: webapp
      DB_PASSWORD: passw0rd
      DB_NAME: webapp
      DB_NAME_TEST: webapp_test
      DB_PORT: 5432
      DB_ENCODING: UTF8
      DB_TIMEZONE: UTC
      DEBUG: 1
